# #ruby encoding: utf-8
# # Create Country

Country.create(name: "V-Pop")
Country.create(name: "K-Pop")
Country.create(name: "US-UK")

# # Create Kind
Kind.create(name: "Nhạc Trẻ", description: "Thể loại EDM")
Kind.create(name: "Cách Mạng", description: "Thể loại Cách Mạng")
Kind.create(name: "Trữ Tình", description: "Thể loại Trữ Tình")
Kind.create(name: "Thiếu Nhi", description: "Thể loại Thiếu Nhi")
Kind.create(name: "EDM", description: "Thể loại Accoutic")
Kind.create(name: "Nhạc Không L", description: "Thể loại Mashup")


# # Create Singer

    Singer.create(name: "Bảo Anh", image: "images/Singer/VietNam/BaoAnh.jpg", story: "Bảo Anh từng là gương mặt ấn tượng trong nhiều cuộc thi âm nhạc dành cho tuổi teen. Năm 2008, Bảo Anh lọt vào top 12 thí sinh vòng chung kết Tiếng ca học đường. Năm 2009, Bảo Anh tiếp tục đoạt giải đồng hạng với Văn Mai Hương tại 'Tiếng Hát Học Đường' với ca khúc 'Ăn khế trả vàng'. Năm 2010, Nguyễn Hoài Bảo Anh tiếp tục đoạt giải triển vọng cuộc thi H2T Icon 2010 do Báo Hoa học trò tổ chức. Năm 2012, Nguyễn Hoài Bảo Anh chinh phục được trái tim của 2 ca sỹ Thu Minh cùng nam ca sỹ nhạc rock Trần Lập trong cuộc thi Giọng hát Việt bằng chất giọng trong sáng và ngọt ngào. Thậm chí, cô cũng còn được ví là Taylor Swift phiên bản Việt lúc thể hiện ca khúc Safe and sound một cách khá trong trẻo, ngọt ngào cùng với hình tượng không khác như một công chúa. Tại thời điểm sau đó, Bảo Anh luôn gắn liền với các bản Ballad ngọt ngào, và truyền cảm. Cô đã nhanh chóng được các khán giả yêu mến với hàng loạt bài hit như là Anh muốn em sống sao, Và em đã biết mình yêu, Em đã từng yêu… Giữ một hình tượng ngây thơ, công chúa vào một thời gian dài, tới năm 2015, Bảo Anh tham gia vào The Remix và quyết định theo đuổi một hình tượng sexy. Bảo Anh ngày càng trưởng thành nhiều hơn ở trong phong cách âm nhạc cũng như là nhan sắc khiến cho nhiều khán giả hâm mộ bất ngờ. Năm 2016 là một năm thành công vượt trội của Bảo Anh cùng với 2 sản phẩm đình đám là Trái tim em cũng biết đau và Yêu một người vô tâm. Đây là 2 ca khúc đã từng làm mưa, làm gió trên khá nhiều bảng xếp hạng âm nhạc và cũng giúp cho nữ ca sĩ giành được khá nhiều giải thưởng uy tín. 2017 cô hợp tác cùng Bùi Anh Tuấn thể hiện ca khúc Thanh Xuân Của Chúng Ta với giai điệu trẻ trung, sôi động và gần đây nhất sau khi chính thức chia tay Hồ Quang Hiếu thì nữ ca sĩ đã phát hành single Sống Xa Anh Chẳng Dễ Dàng.", birthday: "03/09/1992")
    Singer.create(name: "Châu Khải Phong", image: "images/Singer/VietNam/ChauKhaiPhong.jpg", story: "Công ty đại diện: Hải Âu Entertainment Chều cao: 1m73 Cân nặng: 71kg Tài vặt: có thể sáng tác và chơi 2 loại nhạc cụ ghita va organ. Thần tượng: Bằng Kiều và Đàm vĩnh Hưng. Bất ngờ đã tạo tên tuổi bằng ca khúc Anh thích em như xưa hồi vào năm 2011, Châu Khải Phong đã nhanh chóng trở thành một cái tên rất ăn khách, đặc biệt là ở trên các sân khấu phía nam. Sau khi anh tốt nghiệp Đại học Văn hóa Nghệ thuật Quân đội, với những kiến thức về âm nhạc được học ở tại nhà trường cùng với niềm đam mê về ca hát, Châu Khải Phong đã về đầu quân cho công ty giải trí Hải Âu và cũng đã nhanh chóng gửi đến khán giả nhiều những sản phẩm âm nhạc chất lượng. Sau thành công của hàng loạt ca khúc như là Chỉ yêu mình em, Xin đừng cách xa, hay Nụ cười không vui,… Châu Khải Phong đã vừa tung ra album mới có tên gọi là Anh sẽ tập quên. Chỉ sau ít ngày cho ra mắt, album cũng đã nhanh chóng chiếm được những vị trí cao ở trên các bảng xếp hạng âm nhạc online và đã được công chúng đón nhận rất nhiệt tình. Hai album mới nhất của anh trong năm 2017 : Bên Nhau Thật Khó (Single) , Ngắm Hoa Lệ Rơi (Remix). Chia sẻ về dự định ở trong thời gian tới, chàng ca sĩ trẻ đã cho biết: “Sắp tới Phong cũng sẽ có một tour diễn xuyên Việt kỉ niệm 5 năm thành lập công ty Giải trí Hải Âu cùng với nhóm nhạc HKT, HKTM The Five, ca sỹ Phạm Trưởng… Được nghe thấy những tràng pháo tay cỗ vũ rất nồng nhiệt của khán giả ở trong các đêm diễn là niềm hạnh phúc lớn nhất với một ca sĩ trẻ như là Phong. Phong muốn cố gắng đến khi nào mà tất cả mọi người sẽ đều thấy được sự cố gắng của chính mình thì mới thôi…” Để có được vị trí như là hiện tại, Châu Khải Phong cũng đã có một quá trình lao động nghiêm túc và đã đầu tư tâm huyết, đam mê trong suốt thời gian dài. Các giải thưởng đạt được: - Giải 1 tiếng hát HSSV toàn quốc năm 2004 - Giải 2 sao mai khu vưc miền trung 2007 Các Album thành công của Châu Khải Phong: Bên Nhau Thật Khó (Single). Ngắm Hoa Lệ Rơi (Remix). Let’s Go. Chỉ Yêu Mình Em. Số Nghèo… Anh Sẽ Để Em Ra Đi. Xin Đừng Cách Xa. Anh Sẽ Tập Quên. Lời Chúc Không Thật. Châu Khải Phong Dance Remix.", birthday: "30/10/1986")
    Singer.create(name: "Chi Dân", image: "images/Singer/VietNam/ChiDan.jpg", story: "Chi Dân đã có thời gian sinh hoạt ca hát trong nhóm Hero trước đây. Sau một thời gian hoạt động trong nhóm thu được một số kinh nghiệm, Chi Dân quyết định rời nhóm khi hết hợp đồng và theo đuổi con đường ca hát solo. Được mọi người xung quanh nhận xét là sống thân thiện, hòa đồng, cũng với tính cách này đã giúp anh thu hút được một lượng fan hùng hậu. Năm 2013, Chi Dân bất ngờ nổi tiếng sau ca khúc Mất Trí Nhớ. Tưởng chừng đấy chỉ là cơ duyên may thì đến năm 2016, với bài hát Điều anh biết anh đã thực sự được nhiều người biết đến khi có đến hơn 100 triệu người xem Video Audio của ca khúc, hơn 35 triệu người xem MV của ca khúc. 2017, Chi Dân tiếp tục nổi tiếng với các bản hit như 1234, Có được không em và gần đây nhất là Yêu từ phía xa.", birthday: "02/06/1989")
    Singer.create(name: "Đạt G", image: "images/Singer/VietNam/DatG.jpg", story: "Chưa thêm tiểu sử", birthday: "19/5/1990")
    Singer.create(name: "Đức Phúc", image: "images/Singer/VietNam/DucPhuc.jpg", story: "Chưa thêm tiểu sử", birthday: "19/5/1990")
    Singer.create(name: "Erik", image: "images/Singer/VietNam/Erik.jpg", story: "Chưa thêm tiểu sử", birthday: "19/5/1990")
    Singer.create(name: "Hiền Hồ", image: "images/Singer/VietNam/HienHo.jpg", story: "Chưa thêm tiểu sử", birthday: "19/5/1990")
    Singer.create(name: "Hòa Minzy", image: "images/Singer/VietNam/HoaMinzy.jpg", story: "Bảo Anh từng là gương mặt ấn tượng trong nhiều cuộc thi âm nhạc dành cho tuổi teen. Năm 2008, Bảo Anh lọt vào top 12 thí sinh vòng chung kết Tiếng ca học đường. Năm 2009, Bảo Anh tiếp tục đoạt giải đồng hạng với Văn Mai Hương tại 'Tiếng Hát Học Đường' với ca khúc 'Ăn khế trả vàng'. Năm 2010, Nguyễn Hoài Bảo Anh tiếp tục đoạt giải triển vọng cuộc thi H2T Icon 2010 do Báo Hoa học trò tổ chức. Năm 2012, Nguyễn Hoài Bảo Anh chinh phục được trái tim của 2 ca sỹ Thu Minh cùng nam ca sỹ nhạc rock Trần Lập trong cuộc thi Giọng hát Việt bằng chất giọng trong sáng và ngọt ngào. Thậm chí, cô cũng còn được ví là Taylor Swift phiên bản Việt lúc thể hiện ca khúc Safe and sound một cách khá trong trẻo, ngọt ngào cùng với hình tượng không khác như một công chúa. Tại thời điểm sau đó, Bảo Anh luôn gắn liền với các bản Ballad ngọt ngào, và truyền cảm. Cô đã nhanh chóng được các khán giả yêu mến với hàng loạt bài hit như là Anh muốn em sống sao, Và em đã biết mình yêu, Em đã từng yêu… Giữ một hình tượng ngây thơ, công chúa vào một thời gian dài, tới năm 2015, Bảo Anh tham gia vào The Remix và quyết định theo đuổi một hình tượng sexy. Bảo Anh ngày càng trưởng thành nhiều hơn ở trong phong cách âm nhạc cũng như là nhan sắc khiến cho nhiều khán giả hâm mộ bất ngờ. Năm 2016 là một năm thành công vượt trội của Bảo Anh cùng với 2 sản phẩm đình đám là Trái tim em cũng biết đau và Yêu một người vô tâm. Đây là 2 ca khúc đã từng làm mưa, làm gió trên khá nhiều bảng xếp hạng âm nhạc và cũng giúp cho nữ ca sĩ giành được khá nhiều giải thưởng uy tín. 2017 cô hợp tác cùng Bùi Anh Tuấn thể hiện ca khúc Thanh Xuân Của Chúng Ta với giai điệu trẻ trung, sôi động và gần đây nhất sau khi chính thức chia tay Hồ Quang Hiếu thì nữ ca sĩ đã phát hành single Sống Xa Anh Chẳng Dễ Dàng.", birthday: "03/09/1992")
    Singer.create(name: "Hồ Quang Hiếu", image: "images/Singer/VietNam/HoQuangHieu.jpg", story: "Công ty đại diện: Hải Âu Entertainment Chều cao: 1m73 Cân nặng: 71kg Tài vặt: có thể sáng tác và chơi 2 loại nhạc cụ ghita va organ. Thần tượng: Bằng Kiều và Đàm vĩnh Hưng. Bất ngờ đã tạo tên tuổi bằng ca khúc Anh thích em như xưa hồi vào năm 2011, Châu Khải Phong đã nhanh chóng trở thành một cái tên rất ăn khách, đặc biệt là ở trên các sân khấu phía nam. Sau khi anh tốt nghiệp Đại học Văn hóa Nghệ thuật Quân đội, với những kiến thức về âm nhạc được học ở tại nhà trường cùng với niềm đam mê về ca hát, Châu Khải Phong đã về đầu quân cho công ty giải trí Hải Âu và cũng đã nhanh chóng gửi đến khán giả nhiều những sản phẩm âm nhạc chất lượng. Sau thành công của hàng loạt ca khúc như là Chỉ yêu mình em, Xin đừng cách xa, hay Nụ cười không vui,… Châu Khải Phong đã vừa tung ra album mới có tên gọi là Anh sẽ tập quên. Chỉ sau ít ngày cho ra mắt, album cũng đã nhanh chóng chiếm được những vị trí cao ở trên các bảng xếp hạng âm nhạc online và đã được công chúng đón nhận rất nhiệt tình. Hai album mới nhất của anh trong năm 2017 : Bên Nhau Thật Khó (Single) , Ngắm Hoa Lệ Rơi (Remix). Chia sẻ về dự định ở trong thời gian tới, chàng ca sĩ trẻ đã cho biết: “Sắp tới Phong cũng sẽ có một tour diễn xuyên Việt kỉ niệm 5 năm thành lập công ty Giải trí Hải Âu cùng với nhóm nhạc HKT, HKTM The Five, ca sỹ Phạm Trưởng… Được nghe thấy những tràng pháo tay cỗ vũ rất nồng nhiệt của khán giả ở trong các đêm diễn là niềm hạnh phúc lớn nhất với một ca sĩ trẻ như là Phong. Phong muốn cố gắng đến khi nào mà tất cả mọi người sẽ đều thấy được sự cố gắng của chính mình thì mới thôi…” Để có được vị trí như là hiện tại, Châu Khải Phong cũng đã có một quá trình lao động nghiêm túc và đã đầu tư tâm huyết, đam mê trong suốt thời gian dài. Các giải thưởng đạt được: - Giải 1 tiếng hát HSSV toàn quốc năm 2004 - Giải 2 sao mai khu vưc miền trung 2007 Các Album thành công của Châu Khải Phong: Bên Nhau Thật Khó (Single). Ngắm Hoa Lệ Rơi (Remix). Let’s Go. Chỉ Yêu Mình Em. Số Nghèo… Anh Sẽ Để Em Ra Đi. Xin Đừng Cách Xa. Anh Sẽ Tập Quên. Lời Chúc Không Thật. Châu Khải Phong Dance Remix.", birthday: "30/10/1986")
    Singer.create(name: "Hương Tràm", image: "images/Singer/VietNam/HuongTram.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "JayKii", image: "images/Singer/VietNam/Jaykii.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Karik", image: "images/Singer/VietNam/Karik.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Masew", image: "images/Singer/VietNam/Masew.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Only C", image: "images/Singer/VietNam/OnlyC.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Osad", image: "images/Singer/VietNam/Osad.jpg", story: "Bảo Anh từng là gương mặt ấn tượng trong nhiều cuộc thi âm nhạc dành cho tuổi teen. Năm 2008, Bảo Anh lọt vào top 12 thí sinh vòng chung kết Tiếng ca học đường. Năm 2009, Bảo Anh tiếp tục đoạt giải đồng hạng với Văn Mai Hương tại 'Tiếng Hát Học Đường' với ca khúc 'Ăn khế trả vàng'. Năm 2010, Nguyễn Hoài Bảo Anh tiếp tục đoạt giải triển vọng cuộc thi H2T Icon 2010 do Báo Hoa học trò tổ chức. Năm 2012, Nguyễn Hoài Bảo Anh chinh phục được trái tim của 2 ca sỹ Thu Minh cùng nam ca sỹ nhạc rock Trần Lập trong cuộc thi Giọng hát Việt bằng chất giọng trong sáng và ngọt ngào. Thậm chí, cô cũng còn được ví là Taylor Swift phiên bản Việt lúc thể hiện ca khúc Safe and sound một cách khá trong trẻo, ngọt ngào cùng với hình tượng không khác như một công chúa. Tại thời điểm sau đó, Bảo Anh luôn gắn liền với các bản Ballad ngọt ngào, và truyền cảm. Cô đã nhanh chóng được các khán giả yêu mến với hàng loạt bài hit như là Anh muốn em sống sao, Và em đã biết mình yêu, Em đã từng yêu… Giữ một hình tượng ngây thơ, công chúa vào một thời gian dài, tới năm 2015, Bảo Anh tham gia vào The Remix và quyết định theo đuổi một hình tượng sexy. Bảo Anh ngày càng trưởng thành nhiều hơn ở trong phong cách âm nhạc cũng như là nhan sắc khiến cho nhiều khán giả hâm mộ bất ngờ. Năm 2016 là một năm thành công vượt trội của Bảo Anh cùng với 2 sản phẩm đình đám là Trái tim em cũng biết đau và Yêu một người vô tâm. Đây là 2 ca khúc đã từng làm mưa, làm gió trên khá nhiều bảng xếp hạng âm nhạc và cũng giúp cho nữ ca sĩ giành được khá nhiều giải thưởng uy tín. 2017 cô hợp tác cùng Bùi Anh Tuấn thể hiện ca khúc Thanh Xuân Của Chúng Ta với giai điệu trẻ trung, sôi động và gần đây nhất sau khi chính thức chia tay Hồ Quang Hiếu thì nữ ca sĩ đã phát hành single Sống Xa Anh Chẳng Dễ Dàng.", birthday: "03/09/1992")
    Singer.create(name: "Sara Lưu", image: "images/Singer/VietNam/SaraLuu.jpg", story: "Công ty đại diện: Hải Âu Entertainment Chều cao: 1m73 Cân nặng: 71kg Tài vặt: có thể sáng tác và chơi 2 loại nhạc cụ ghita va organ. Thần tượng: Bằng Kiều và Đàm vĩnh Hưng. Bất ngờ đã tạo tên tuổi bằng ca khúc Anh thích em như xưa hồi vào năm 2011, Châu Khải Phong đã nhanh chóng trở thành một cái tên rất ăn khách, đặc biệt là ở trên các sân khấu phía nam. Sau khi anh tốt nghiệp Đại học Văn hóa Nghệ thuật Quân đội, với những kiến thức về âm nhạc được học ở tại nhà trường cùng với niềm đam mê về ca hát, Châu Khải Phong đã về đầu quân cho công ty giải trí Hải Âu và cũng đã nhanh chóng gửi đến khán giả nhiều những sản phẩm âm nhạc chất lượng. Sau thành công của hàng loạt ca khúc như là Chỉ yêu mình em, Xin đừng cách xa, hay Nụ cười không vui,… Châu Khải Phong đã vừa tung ra album mới có tên gọi là Anh sẽ tập quên. Chỉ sau ít ngày cho ra mắt, album cũng đã nhanh chóng chiếm được những vị trí cao ở trên các bảng xếp hạng âm nhạc online và đã được công chúng đón nhận rất nhiệt tình. Hai album mới nhất của anh trong năm 2017 : Bên Nhau Thật Khó (Single) , Ngắm Hoa Lệ Rơi (Remix). Chia sẻ về dự định ở trong thời gian tới, chàng ca sĩ trẻ đã cho biết: “Sắp tới Phong cũng sẽ có một tour diễn xuyên Việt kỉ niệm 5 năm thành lập công ty Giải trí Hải Âu cùng với nhóm nhạc HKT, HKTM The Five, ca sỹ Phạm Trưởng… Được nghe thấy những tràng pháo tay cỗ vũ rất nồng nhiệt của khán giả ở trong các đêm diễn là niềm hạnh phúc lớn nhất với một ca sĩ trẻ như là Phong. Phong muốn cố gắng đến khi nào mà tất cả mọi người sẽ đều thấy được sự cố gắng của chính mình thì mới thôi…” Để có được vị trí như là hiện tại, Châu Khải Phong cũng đã có một quá trình lao động nghiêm túc và đã đầu tư tâm huyết, đam mê trong suốt thời gian dài. Các giải thưởng đạt được: - Giải 1 tiếng hát HSSV toàn quốc năm 2004 - Giải 2 sao mai khu vưc miền trung 2007 Các Album thành công của Châu Khải Phong: Bên Nhau Thật Khó (Single). Ngắm Hoa Lệ Rơi (Remix). Let’s Go. Chỉ Yêu Mình Em. Số Nghèo… Anh Sẽ Để Em Ra Đi. Xin Đừng Cách Xa. Anh Sẽ Tập Quên. Lời Chúc Không Thật. Châu Khải Phong Dance Remix.", birthday: "30/10/1986")
    Singer.create(name: "Sơn Tùng MTP", image: "images/Singer/VietNam/SonTung.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Soobin Hoàng Sơn", image: "images/Singer/VietNam/SoobinHoangSon.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
    Singer.create(name: "Trịnh Thăng Bình", image: "images/Singer/VietNam/TrinhThangBinh.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")

# # Create Musician
Musician.create(name: "Kai Đinh", image: "images/Musician/VietNam/KaiDinh.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Khắc Hưng", image: "images/Musician/VietNam/KhacHung.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Nguyễn Đình Vũ", image: "images/Musician/VietNam/NguyenDinhVu.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Nguyễn Phúc Thiện", image: "images/Musician/VietNam/NguyenPhucThien.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Phan Mạnh Quỳnh", image: "images/Musician/VietNam/PhanManhQuynh.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Rhymatic", image: "images/Musician/VietNam/Rhymastic.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Sơn Tùng MTP", image: "images/Musician/VietNam/KaiDinh.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Tiên Cookie", image: "images/Musician/VietNam/TienCookie.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Tiên Tiên", image: "images/Musician/VietNam/TienTien.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")
Musician.create(name: "Vũ Cát Tường", image: "images/Musician/VietNam/VuCatTuong.jpg", story: "Tiểu sử Trịnh Thăng Bình", birthday: "19/5/1990")


# # Create Album
Album.create(name: "Ai Khóc Nổi Đau Này", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Chạm Đáy Nổi Đau", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Chạy Ngay Đi", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Đóa Hoa Hồng", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Em Của Ngày Hôm Qua", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Kém Duyên", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Lạc Trôi", image: "images/Album/VietNam/AiKhocNoiDauNay.jpg", issue: "21/5/2018")
Album.create(name: "Lỡ Như Anh Yêu Em", image: "images/Album/VietNam/LoNhuAnhYeuEm.jpg", issue: "21/5/2018")
Album.create(name: "Ngắm Hoa Lệ Rơi", image: "images/Album/VietNam/NgamHoaLeRoi.jpg", issue: "21/5/2018")
Album.create(name: "Phía Sau Một Cô Gái", image: "images/Album/VietNam/PhiaSauMotCoGai.jpg", issue: "21/5/2018")
Album.create(name: "Sống Xa Anh Chẳng Dể Dàng", image: "images/Album/VietNam/SongXaAnhChangDeDang.jpg", issue: "21/5/2018")
Album.create(name: "Thấy Là Yêu Thương", image: "images/Album/VietNam/ThayLaYeuThuong.jpg", issue: "21/5/2018")

# # Create User
User.create(account: "ac1", password: "pw1", display_name: "P", position: "1")
User.create(account: "ac2", password: "pw2", display_name: "P", position: "1")
User.create(account: "ac3", password: "pw3", display_name: "P", position: "1")
User.create(account: "ac4", password: "pw4", display_name: "P", position: "1")
User.create(account: "ac5", password: "pw5", display_name: "P", position: "1")
User.create(account: "ac6", password: "pw6", display_name: "P", position: "1")

# # Create  Song
Song.create(name: "Chạy Ngay Đi", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99999", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Rồi Người Thương Cũng", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99998", singer_id: "2", musician_id: "2", kind_id: "2", country_id: "1", album_id: "2", user_id:"2" )
Song.create(name: "Đừng Như Thói Quen", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99997", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Người Âm Phủ", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99996", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Chạm Đáy Nổi Đau", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99995", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Cô Gái M52", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99994", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Rời Bỏ", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99993", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Ngắm Hoa Lệ Rơi", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99992", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Rồi Người Thương Cũng Hóa Người Dưng", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99991", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Cùng Anh", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99990", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Buồn Của Anh", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99989", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Hôm Nay Tôi Buồn", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99988", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Người Lạ Ơi", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99987", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Ý Em Sao", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99986", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Vì Yêu Là Nhớ", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99985", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )
Song.create(name: "Pinocchio", link: "http://", lyric: "Chưa có", issue: "12/5/1997", view: "99984", singer_id: "1", musician_id: "1", kind_id: "1", country_id: "1", album_id: "1", user_id:"1" )


# # Create Comment
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "1", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "2", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "3", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "4", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "5", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "6", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "7", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "8", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "9", user_id: "3")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "9", user_id: "3")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "10", user_id: "2")
Comment.create(content: "Comment cho vui", time: "21/5/2018", song_id: "11", user_id: "1")


# # Create History
History.create(action: "nghe", object: "bài hát", user_id: "2");
History.create(action: "comment", object: "bài hát", user_id: "3");
History.create(action: "update", object: "bài hát", user_id: "2");
History.create(action: "nghe", object: "bài hát", user_id: "2");
History.create(action: "comment", object: "bài hát", user_id: "1");
History.create(action: "comment", object: "bài hát", user_id: "2");
History.create(action: "nghe", object: "bài hát", user_id: "2");
